# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: events-api # NOTE: update this with your service name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: nodejs8.10
  stage: beta
  region: eu-west-2

# you can overwrite defaults here
#  stage: dev
#  region: us-east-1

# you can add statements to the Lambda function's IAM Role here
#  iamRoleStatements:
#    - Effect: "Allow"
#      Action:
#        - "s3:ListBucket"
#      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
#    - Effect: "Allow"
#      Action:
#        - "s3:PutObject"
#      Resource:
#        Fn::Join:
#          - ""
#          - - "arn:aws:s3:::"
#            - "Ref" : "ServerlessDeploymentBucket"
#            - "/*"

# you can define service wide environment variables here
#  environment:
#    variable1: value1

# you can add packaging information here
#package:
#  include:
#    - include-me.js
#    - include-me-dir/**
#  exclude:
#    - exclude-me.js
#    - exclude-me-dir/**

functions:
  getAll:
    handler: handler.getAll
    events:
          - http:
              path: events # path will be domain.name.com/dev/notes
              method: get
              cors: true

  filterBy:
    handler: handler.filterBy
    events:
          - http:
              path: events/filter/{limit}/{page}
              method: get
              cors: true
              request:
                parameters:
                  paths:
                    limit: true
                    page: true
  trending:
    handler: handler.trending
    events:
          - http:
              path: events/trending/{limit}
              method: get
              cors: true
              request:
                parameters:
                  paths:
                    limit: true
  history:
    handler: handler.history
    events:
          - http:
              path: events/history/{limit}
              method: post
              cors: true
              request:
                parameters:
                  paths:
                    limit: true
plugins:
  - serverless-offline